import Vue from 'vue'


// Load Vuetify with some standard components
import Vuetify, {
    VApp,
    VAppBar,
    VAppBarNavIcon,
    VAvatar,
    VBtn,
    VCard,
    VCardActions,
    VCardSubtitle,
    VCardText,
    VCardTitle,
    VCol,
    VContainer,
    VDataTable,
    VDatePicker,
    VDialog,
    VExpansionPanel,
    VExpansionPanelContent,
    VExpansionPanelHeader,
    VExpansionPanels,
    VFooter,
    VForm,
    VIcon,
    VLayout,
    VList,
    VListItem,
    VListItemAction,
    VListItemContent,
    VListItemIcon,
    VListItemSubtitle,
    VListItemTitle,
    VMain,
    VMenu,
    VNavigationDrawer,
    VProgressLinear,
    VRow,
    VSelect,
    VSimpleTable,
    VSpacer,
    VSwitch,
    VTab,
    VTabItem,
    VTabs,
    VTabsItems,
    VTextField,
    VTimePicker,
    VToolbar,
    VToolbarItems,
    VToolbarTitle,
    VTooltip,
    VChip,
} from 'vuetify/lib'

Vue.use(Vuetify, {
    components: {
        VApp,
        VAppBar,
        VAppBarNavIcon,
        VAvatar,
        VBtn,
        VCard,
        VCardActions,
        VCardSubtitle,
        VCardText,
        VCardTitle,
        VCol,
        VContainer,
        VDataTable,
        VDatePicker,
        VDialog,
        VExpansionPanel,
        VExpansionPanelContent,
        VExpansionPanelHeader,
        VExpansionPanels,
        VFooter,
        VForm,
        VIcon,
        VLayout,
        VList,
        VListItem,
        VListItemAction,
        VListItemContent,
        VListItemIcon,
        VListItemSubtitle,
        VListItemTitle,
        VMain,
        VMenu,
        VNavigationDrawer,
        VProgressLinear,
        VRow,
        VSelect,
        VSimpleTable,
        VSpacer,
        VSwitch,
        VTab,
        VTabItem,
        VTabs,
        VTabsItems,
        VTextField,
        VTimePicker,
        VToolbar,
        VToolbarItems,
        VToolbarTitle,
        VTooltip,
        VChip,
    }
});


// Use theme defined in file
import theme from "./theme";
const opts = {
  theme: theme
}

export default new Vuetify(opts)
